import {
  BadgeCheck,
  Boxes,
  Clapperboard,
  FileText,
  Palette,
  PenLine,
  ScanEye,
  ShieldAlert,
  Sparkles,
  Target,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { NodeKind } from "@/lib/creative-os/types";

export const KIND_META: Record<
  NodeKind,
  { label: string; icon: LucideIcon; text: string; bg: string; border: string; dot: string; stroke: string }
> = {
  input: {
    label: "Input",
    icon: FileText,
    text: "text-kind-input",
    bg: "bg-kind-input/10",
    border: "border-kind-input/30",
    dot: "bg-kind-input",
    stroke: "var(--kind-input)",
  },
  insight: {
    label: "Insight",
    icon: Users,
    text: "text-kind-insight",
    bg: "bg-kind-insight/10",
    border: "border-kind-insight/30",
    dot: "bg-kind-insight",
    stroke: "var(--kind-insight)",
  },
  strategy: {
    label: "Strategy",
    icon: Target,
    text: "text-kind-strategy",
    bg: "bg-kind-strategy/10",
    border: "border-kind-strategy/30",
    dot: "bg-kind-strategy",
    stroke: "var(--kind-strategy)",
  },
  creative: {
    label: "Creative",
    icon: Sparkles,
    text: "text-kind-creative",
    bg: "bg-kind-creative/10",
    border: "border-kind-creative/30",
    dot: "bg-kind-creative",
    stroke: "var(--kind-creative)",
  },
  copy: {
    label: "Copy",
    icon: PenLine,
    text: "text-kind-copy",
    bg: "bg-kind-copy/10",
    border: "border-kind-copy/30",
    dot: "bg-kind-copy",
    stroke: "var(--kind-copy)",
  },
  visual: {
    label: "Art direction",
    icon: Palette,
    text: "text-kind-visual",
    bg: "bg-kind-visual/10",
    border: "border-kind-visual/30",
    dot: "bg-kind-visual",
    stroke: "var(--kind-visual)",
  },
  prompt: {
    label: "Generation",
    icon: ScanEye,
    text: "text-kind-prompt",
    bg: "bg-kind-prompt/10",
    border: "border-kind-prompt/30",
    dot: "bg-kind-prompt",
    stroke: "var(--kind-prompt)",
  },
  motion: {
    label: "Motion",
    icon: Clapperboard,
    text: "text-kind-motion",
    bg: "bg-kind-motion/10",
    border: "border-kind-motion/30",
    dot: "bg-kind-motion",
    stroke: "var(--kind-motion)",
  },
  guardrail: {
    label: "Governance",
    icon: ShieldAlert,
    text: "text-kind-guardrail",
    bg: "bg-kind-guardrail/10",
    border: "border-kind-guardrail/30",
    dot: "bg-kind-guardrail",
    stroke: "var(--kind-guardrail)",
  },
  qa: {
    label: "Quality",
    icon: BadgeCheck,
    text: "text-kind-qa",
    bg: "bg-kind-qa/10",
    border: "border-kind-qa/30",
    dot: "bg-kind-qa",
    stroke: "var(--kind-qa)",
  },
  export: {
    label: "Output",
    icon: Boxes,
    text: "text-kind-export",
    bg: "bg-kind-export/10",
    border: "border-kind-export/30",
    dot: "bg-kind-export",
    stroke: "var(--kind-export)",
  },
};
